stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/energy_dataset_raw.xlsx
    outs:
    - data/raw/energy_dataset_raw.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/energy_dataset_raw.csv
    outs:
    - data/processed/train_energy_efficiency.csv
    - data/processed/test_energy_efficiency.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_energy_efficiency.csv
    - data/processed/test_energy_efficiency.csv
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.min_samples_split
    metrics:
    - reports/params.json:
        cache: false
    - reports/scores.json:
        cache: false
    outs:
    - saved_models/rf_model.joblib