base:
  project: energy_efficiency_project
  random_state: 42
  target_col_1: Heating_Load
  target_col_2: Cooling_Load

data_source:
  s3_source: data_given/energy_dataset_raw.xlsx

load_data:
  raw_dataset_csv: data/raw/energy_dataset_raw.csv

split_data:
  train_path: data/processed/train_energy_efficiency.csv
  test_path: data/processed/test_energy_efficiency.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 100
      min_samples_split: 2

model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json