base:
  project: energy_efficiency_project
  random_state: 42
  target_col: Y1, Y2

data_source:
  s3_source: data_given/energy_dataset_raw.xlsx

load_data:
  raw_dataset_csv: data/raw/energy_dataset_raw.csv

split_data:
  train_path: data/processed/train_energy_efficiency.csv
  test_path: data/processed/test_energy_efficiency.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models